config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # root to: 'home#index'
  root to: 'rooms#home'
  
  get 'users/account' => 'users#show'
  get 'users/profile' => 'users#edit'
  post 'users/:id/update' => 'users#update'
  resources :users, only: [:account, :profile, :update]
  get 'rooms/posts' => 'rooms#index'
  # resources :rooms
  
  resources :rooms do
    get :home,   on: :collection
    get :search, on: :collection
  end
  
  resources :reservations

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/reservation.rb
class Reservation < ApplicationRecord
  belongs_to :user
  belongs_to :room
  
  validates :start_date,    presence: true
  validates :end_date,      presence: true
  validates :person_num,    presence: true
  validates :total_price,   presence: true
  
  validate :date_before_start
  validate :start_end_check
  
  def date_before_start
    errors.add(:start_date, "は今日以降のものを選択してください") if
    self.start_date < Date.today
  end

  def start_end_check
    errors.add(:end_date, "は開始日より前の日付は登録できません。") unless
    self.start_date < self.end_date 
  end
  
end

app/models/room.rb
class Room < ApplicationRecord
  belongs_to :user
  has_many :reservations
  mount_uploader :image, ImageUploader
  
  validates :name,    presence: true
  validates :content, presence: true
  validates :price,   presence: true
  validates :address, presence: true
  validates :image,   presence: true
  
end

app/models/user.rb
class User < ApplicationRecord
  has_many :rooms
  has_many :reservations, dependent: :destroy
  mount_uploader :image, ImageUploader
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  validates :email, uniqueness: true
  validates :name,  uniqueness: true, presence: true
  
  # validates :image,        presence: true, if: :current_user?
  # validates :introduction, presence: true, if: :user_signed_in?
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    added_attrs = [ :email, :name, :password, :password_confirmation ]
    devise_parameter_sanitizer.permit :sign_up, keys: added_attrs
    devise_parameter_sanitizer.permit :account_update, keys: added_attrs
    devise_parameter_sanitizer.permit :sign_in, keys: added_attrs
  end
  
  def after_sign_in_path_for(resource) 
    users_profile_path
  end
  
  #ログイン後のリダイレクト先
  # def after_sign_in_path_for(resource)
  #   root_path
  # end 
  
  #アカウント登録後のリダイレクト先
  # def after_sign_up_path_for(resource)
  #   users_profile_path
  # end
end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
  
  def index
    @room = Room.all.includes(:reservations)
  end
  
  def show
    @reservation = Reservation.find(params[:id])
  end
  
  def new
    @room = Room.find(params[:room_id])
    @reservation = current_user.reservations.new
    
    @start_date = params[:start_date]
    @end_date = params[:end_date]
    @use_days = (@end_date.to_date - @start_date.to_date).to_s.chomp('/1')
    @person_num= params[:person_num]
    @total_price = @room.price.to_i * @use_days.to_i * @person_num.to_i
  end
  
  def create
    @room = Room.new
    @reservation = current_user.reservations.build(reservation_params)
    if @reservation.save
      flash[:notice] = "予約を完了しました"
      redirect_to reservation_path(@reservation)
    else
      render :new
    end
    
  end
  
  private
  
    def reservation_params
        params.require(:reservation).permit(:start_date, :end_date, :person_num, :total_price, :user_id, :room_id)
    end
    
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :set_q, only: [:home, :search]
  
  def home
  end
  
  def index
    @rooms = Room.all
  end
  
  def show
    @room = Room.find(params[:id])
  end
  
  def new
    @room = current_user.rooms.new
  end
  
  def create
    @room = current_user.rooms.build(room_params)
    if @room.save
      flash[:notice] = "部屋が作成されました。"
      redirect_to @room
    else
      render :new
    end
  end
  
  def edit
  end
  
  def update
  end
  
  def destroy
  end
  
  def search
    @results = @q.result
  end

  private

    def room_params
      params.require(:room).permit(:name, :content, :price, :address, :image)
    end
    
    def set_q
      @q = Room.ransack(params[:q])
    end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  #アカウント登録後のリダイレクト先
  def after_sign_up_path_for(resource)
    users_profile_path
  end
  
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::RegistrationsController
  #ログイン後のリダイレクト先
  def after_sign_in_path_for(resource)
    root_path
  end 
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, only: [:show, :edit, :update]
  # before_action :logged_in_user, only: [:edit, :update]
  
  def show
    # @user = User.find(params[:id])
    @user = current_user
  end
  
  def edit
    # @user = User.find(id: params[:id])
    @user = current_user
  end
  
  def update
    @user = current_user
    # @user = User.find(params[:id])
    if @user.image && @user.update(user_params)
      flash[:notice] = "プロフィールが更新されました"
      redirect_to users_profile_path
    else
      render :edit
    end
  end
  
  private
    def user_params
      params.require(:user).permit(:image, :name, :introduction)
    end
    
    # ログイン済みユーザーかどうか確認
    # def logged_in_user
    #   unless logged_in?
    #     flash[:danger] = "Please log in."
    #     redirect_to root_path
    #   end
    # end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/reservations_helper.rb
module ReservationsHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_devise.html.erb
<% if flash[:notice] %>
  <div class="notice"><%= notice %></div>
<% end %>
<% if flash[:alert] %>
  <div class="alert"><%= alert %></div>
<% end %>

app/views/layouts/_footer.html.erb
<footer class="footer">
	<p>© 2020 POTEPAN.INC.</p>
</footer>

app/views/layouts/_header.html.erb
<header class="header">
	<div class="header-inner">
		<div class="header-left-nav">
			<a href="/"><img alt="サイトのロゴ画像" src="/assets/logo.png" /></a>
			
				<%= form_with url: search_rooms_path do |f| %>
				
					<div class="header-sharch d-lg-inline-block d-none">
						<%= f.text_field :name, class: "form-control", :placeholder => "エリア" %>
						<i class="fas fa-map-marker-alt"></i>
					</div>
					
					<div class="header-sharch d-lg-inline-block d-none">
						<%= f.text_field :name, class: "form-control", :placeholder => "キーワード" %>
						<i class="fas fa-search"></i>
					</div>
					<%= f.submit '', class: "d-none" %>
					
				<% end %>

		</div>
		<div class="header-right-nav">
			<% if user_signed_in? %>
				<div class="nav-item d-sm-inline-block d-none">
					<%= current_user.name %>
				</div>
					<div class="nav-item">
						<% if current_user.image? %>
						  <%= image_tag current_user.image.url, alt: "アイコン画像", class: "mx-3 p-1 host-icon nav-trigger" %>
						<% else %>
						  <%= image_tag "default_icon.jpg", alt: "メニュー", class: "mx-3 p-1 host-icon nav-trigger" %>
						<% end %>
						<ul class="header-nav-menu">
							<li><%= link_to "ルーム登録", new_room_path %></li>

							<li><%= link_to "予約済みルーム一覧", reservations_path %></li>
							
							<li><%= link_to "登録済みルーム一覧", rooms_path %></li>
							
							<li><%= link_to "設定", users_account_path %></li>
							
							<li><%= link_to "ログアウト", destroy_user_session_path, method: :delete %></li>
						</ul>
					</div>
				</div>
   			<% else %>
   				<div class="nav-item">
					<%= link_to "ログイン", new_user_session_path, class: "btn btn-primary my-2 mx-3" %>
					<%= link_to "登録する", new_user_registration_path, class: "btn btn-secondary" %>
				</div>
			<% end %>
		</div>
	</div>
</header>

app/views/layouts/_shim.html.erb
<script>
  $(function() {
    $('.nav-trigger').click(function() {
          $('.header-nav-menu').toggle(1500);
      })
  });
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>InnShareApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.3/css/all.css">
  </head>

  <body>
    <%= render 'layouts/header' %>
    <div class="clearfix"></div>
    <%= render 'layouts/shim' %>
    <div class="notifications">
    <%= render 'layouts/devise' %>
    </div>
    <%= yield %>
    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/reservations/_form.html.erb
<div class="col-md-4">
	<div class="room-show-nav">
		<h5 class="price-icon"><%= @room.price %> / 日</h5>
		<div class="room-show-date-select">
			<%= form_with model: @reservations, url: new_reservation_path, method: :get do |f| %>
				
				<%= f.label :start_date, "開始日" %>
				<%= f.date_field :start_date, class: "form-control mb-4" %>
				
				<%= f.label :end_date, "終了日" %>
				<%= f.date_field :end_date, class: "form-control mb-4" %>
				
				<%= f.label :person_num, "人数" %>
				<%= f.number_field :person_num, class: "form-control mb-4" %>
				
				<%= f.hidden_field :room_id, value:@room.id %>
				
				<%= f.submit "予約する", class: "btn btn-primary form-control" %>
				
			<% end %>
		</div>
	</div>
</div>

app/views/reservations/index.html.erb
<div class="container-fiuld reservations">
	<h4 class="pb-4">予約済みルーム一覧</h4>
	<table>
		<thead>
			<tr align="center">
				<th>ルーム画像</th>
				<th>ルーム名</th>
				<th>ルーム紹介</th>
				<th>合計料金</th>
				<th>開始日</th>
				<th>終了日</th>
				<th>予約確定日時</th>
			</tr>
		</thead>
		<tbody>
			<% @room.each do |room| %>
				<% room.reservations.each do |reservation| %>
					<tr>
						<td>
							<%= link_to image_tag("#{room.image}", onerror: "this.onerror=null;this.src='/assets/room01.jpg';", class: "reservations-image" ),
							room_path(room) %>
						</td>
						<td class="posts-name">
							<%= link_to room.name, room_path(room) %>
						</td>
						<td class="posts-content"><%= room.content %></td>
						<td class="price-icon"><%= reservation.total_price %></td>
						<td><%= reservation.start_date %></td>
						<td><%= reservation.end_date %></td>
						<td><%= reservation.updated_at %></td>
					</tr>
				<% end %>
			<% end %>
		</tbody>
	</table>
</div>

app/views/reservations/new.html.erb
<div class="row">
	<div class="col-6 offset-3">
		<div class="reservations-new-nav">
			<h4 class="reservations-new-check-content">予約内容確認</h4>
			<h5 class="price-icon"><%= @room.price %> / 日</h5>
			<div class="reservations-new-date-select">
			  
			  <%= form_with model: @reservation, method: :post do |f| %>
			  
				  <% @reservation.errors.full_messages.each do |message| %>
				  	<p><%= message %></p>
					<% end %>
				
				  <%= f.hidden_field :user_id, value: current_user.id %>
				  <%= f.hidden_field :room_id, value: @room.id %>
					
					<%= f.label :start_date, "開始日" %>
					<%= f.text_field :start_date, value: @start_date, class: "form-control mb-4", :readonly => true %>
					
					<%= f.label :end_date, "終了日" %>
					<%= f.text_field :end_date, value: @end_date, class: "form-control mb-4", :readonly => true %>
					
					<h6 class="reservations-new-check-content">使用日数 : <%= @use_days %>日</h6>
					
					<h6 class="reservations-new-check-content">人数 : <%= f.hidden_field :person_num, value: @person_num %><%= @person_num %>人</h6>
					
					<%= f.label :total_price, "合計金額" %>
					<%= f.text_field :total_price, value: @total_price, class: "form-control mb-4", :readonly => true %>
					
					<p class="reservations-new-check-content">上記内容でよろしければ「予約を確定」を押してください</p>
					
					<%= f.submit "予約を確定", class: "btn btn-primary form-control my-3" %>
					
					<%= link_to "ルーム詳細に戻る", "/rooms/#{@room.id}", class: "btn btn-secondary form-control" %>
					
				<% end %>
				
			</div>
		</div>
	</div>
</div>

app/views/reservations/show.html.erb
<div class="container-fiuld user">
	<div class="row">
		<div class="col-md-12 user-view">
			<div class="user-view-box">
				<div class="update-content">
					<div class="row">
						<label class="col-md-3" for="room">予約した部屋</label>
						<div class="col-md-9">
							<%= link_to current_user.name, "/rooms/#{@reservation.room_id}" %>
						</div>
					</div>
				</div>
				<div class="update-content">
					<div class="row">
						<label class="col-md-3" for="start_date">開始日</label>
						<div class="col-md-9">
							<%= @reservation.start_date %>
						</div>
					</div>
				</div>
				<div class="update-content">
					<div class="row">
						<label class="col-md-3" for="end_date">終了日</label>
						<div class="col-md-9">
							<%= @reservation.end_date %>
						</div>
					</div>
				</div>
				<div class="update-content">
					<div class="row">
						<label class="col-md-3" for="end_date">価格</label>
						<div class="col-md-9">
							<%= @reservation.total_price %>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>

app/views/rooms/home.html.erb
<div class="top">
	<div class="top-main">
		<div class="container">
			<div class="row col-lg-6">
				<div class="form-fream">
					<div class="form-area">
						<p class="form-area-title mb-4">Potepan Shareでまだ体験したことのない旅をしよう</p>
						
						<%= search_form_for @q, url: search_rooms_path do |f| %>
						  <%= f.label :name_cont, 'エリア' %>
						  <%= f.search_field :name_cont, class: "form-control mb-4", :placeholder => "東京" %>
						  <%= f.submit '探す', class: "form-control btn-primary mb-4" %>
						<% end %>
						
					</div>
				</div>
			</div>
		</div>
	</div>
	<div class="container">
		<div class="panel-area m-5">
			<h1 class="section-title">おすすめのエリア</h1>
			<div class="row">
				
				<div class="panel-item col-lg-3 col-6">
					<span>東京</span>
					<%= link_to  controller: "rooms", action: "search", q: { name_cont: '東京'} do %>
						<%= image_tag("/assets/img_tokyo.jpg", class: "panel-image") %>
					<% end %>
					<div class="shadow"></div>
				</div>
				
				<div class="panel-item col-lg-3 col-6">
					<span>大阪</span>
					<%= link_to  controller: "rooms", action: "search", q: { name_cont: '大阪'} do %>
						<%= image_tag("/assets/img_osaka.jpg", class: "panel-image") %>
					<% end %>
					<div class="shadow"></div>
				</div>
				
				<div class="panel-item col-lg-3 col-6">
					<span>京都</span>
					<%= link_to  controller: "rooms", action: "search", q: { name_cont: '京都'} do %>
						<%= image_tag("/assets/img_kyoto.jpg", class: "panel-image") %>
					<% end %>
					<div class="shadow"></div>
				</div>
				
				<div class="panel-item col-lg-3 col-6">
					<span>札幌</span>
					<%= link_to  controller: "rooms", action: "search", q: { name_cont: '札幌'} do %>
						<%= image_tag("/assets/img_sapporo.jpg", class: "panel-image") %>
					<% end %>
					<div class="shadow"></div>
				</div>
				
			</div>
		</div>
	</div>
</div>

app/views/rooms/index.html.erb
<div class="container-fiuld room-posts">
	<h4 class="pb-4">登録済みルーム一覧</h4>
	<table>
		<thead>
			<tr align="center">
				<th>ルーム画像</th>
				<th>ルーム名</th>
				<th>ルーム紹介</th>
				<th>料金</th>
				<th>作成日</th>
			</tr>
		</thead>
		<tbody>
		  <% @rooms.each do |room| %>
			<tr>
				<td>
				  <%= link_to image_tag("#{room.image}", class: "room-posts-image" ), room_path(room) %>
				</td>
				<td class="posts-name">
				  <%= link_to room.name, room_path(room) %>
				</td>
				<td class="posts-content"><%= room.content %></td>
				<td class="price-icon"><%= room.price %></td>
				<td><%= room.created_at %></td>
			</tr>
			<% end %>
		</tbody>
	</table>
</div>

app/views/rooms/new.html.erb
<div class="container-fiuld room-new">
	<div class="row">
		<div class="col-lg-2 room-nav room-nav-pc d-lg-block d-none">
			<ul>
			  <li class="active"><%= link_to "基本情報", new_room_path %></li>
			</ul>
		</div>
		<div class="col-lg-2 room-nav room-nav-mobile d-lg-none">
			<ul>
			  <li class="active"><%= link_to "基本情報", new_room_path %></li>
			</ul>
		</div>
		<div class="col-lg-10 room-view">
			<div class="room-view-box">
				<%= form_with model: @room do |f| %>
			  
					<div class="update-content">
						<div class="row">
							<h5>ルーム情報登録</h5>
						</div>
					</div>
					<div class="update-content">
						<div class="row">
							<%= f.label :name, class: "col-md-3 required-a" %>
							<%= f.text_field :name, class: "form-control mb-4 col-md-9", :placeholder => "ルーム名を入力" %>
						</div>
					</div>
					<div class="update-content">
						<div class="row">
							<%= f.label :content, class: "col-md-3 required-a" %>
							<%= f.text_area :content, rows: 5, class: "form-control mb-4 col-md-9", :placeholder => "ルーム説明を入力" %>
						</div>
					</div>
					<div class="update-content">
						<div class="row">
						  <%= f.label :price, class: "col-md-3 required-a" %>
							<%= f.number_field :price, class: "form-control mb-4 col-md-9", :placeholder => "一日あたりの料金を入力" %>
						</div>
					</div>
					<div class="update-content">
						<div class="row">
						  <%= f.label :address, class: "col-md-3 required-a"%>
							<%= f.text_field :address, class: "form-control mb-4 col-md-9", :placeholder => "住所を入力" %>
						</div>
					</div>
					<div class="update-content">
						<div class="row">
							<%= f.label :image, class: "col-md-3 required-a" %>
							<%= f.file_field :image, class: "mb-4 col-md-9", :placeholder => "ルーム画像をアップロード" %>
						</div>
					</div>
					<div class="update-content">
						<div class="row">
						  <%= f.submit "登録", class: "col-md-2 btn btn-primary mx-3" %>
						</div>
					</div>
					
				<% end %>
			</div>
		</div>
	</div>
</div>

app/views/rooms/search.html.erb
<div class="container-fiuld room">
	<h4 class="pb-4">検索結果：
	  <% if @results == nil %>
      0件
    <% else %>
      <%= @results.count %>件
    <% end %>
	</h4>
	<div class="row">
    <% @results.each do |room| %>
		<div class="col-sm-6 col-lg-4 col-xl-3">
			<div class="room-frame-inner">
					<div class="room-image-out">
					  <%= link_to image_tag("#{room.image}", onerror: "this.onerror=null;this.src='/assets/room01.jpg';", alt: "部屋画像", class: "room-image" ),
					  room_path(room) %>
					</div>
					<div class="room-profile">
						<p class="room-profile-name"><%= room.name %></p>
						<p class="room-profile-city"><%= room.content %></p>
						<p class="room-profile-price price-icon"><%= room.price %></p>
					</div>
				</a>
			</div>
		</div>
		<% end %>
	</div>
</div>

app/views/rooms/show.html.erb
<div class="container room-show">
	<div class="row">
		<div class="col-md-8">
			<%= image_tag @room.image.url, onerror: "this.onerror=null;this.src='/assets/room01.jpg';", alt: "部屋画像", class: "room-show-image" %>

			<div class="room-show-detile">
				<div class="room-show-detile-icon">
					<a href="/">
					<% if current_user.image? %>
						  <%= image_tag current_user.image.url, class: "host-icon" %>
					<% else %>
						  <%= image_tag "default_icon.jpg", class: "host-icon" %>
					<% end %>
					</a>
				</div>
				<div class="room-show-profile">
					<p class="room-show-profile-name"><%= @room.name %></p>
					<p class="room-show-profile-address"><%= @room.address %></p>
				</div>
			</div>
			<p class="room-show-detile-content"><%= @room.content %></p>
		</div>
		
		<%= render 'reservations/form' %>
		
	</div>
</div>

app/views/users/edit.html.erb
<div class="container-fiuld user">
	<div class="row">
		<div class="col-lg-2 user-nav user-nav-pc d-lg-block d-none">
			<ul>
				<li class=""><%= link_to "アカウント", users_account_path %></li>
				<li class="active"><%= link_to "プロフィール", users_profile_path %></li>
			</ul>
		</div>
		<div class="col-lg-2 user-nav user-nav-mobile d-lg-none">
			<ul>
				<li class=""><%= link_to "アカウント", users_account_path %></li>
				<li class="active"><%= link_to "プロフィール", users_profile_path %></li>
			</ul>
		</div>
		<div class="col-lg-10 user-view">
			<div class="user-view-box">
				<div class="update-content">
					<div class="row">
						<h5>プロフィール</h5>
					</div>
				</div>
				<%= form_with model: @user do |f| %>
					<div class="update-content">
						<div class="row">
							<div class="col-md-6 offset-md-3">
								<div class="icon-box">
									<% if @user.image? %>
									  <%= image_tag @user.image.url, alt: "アイコン画像", class: "icon-image host-icon" %>
									<% else %>
									  <%= image_tag "default_icon.jpg", alt: "アイコン画像", class: "icon-image host-icon" %>
									<% end %>
								</div>
							</div>
						</div>
					</div>
					<div class="update-content">
						<div class="row">
							<%= f.label :image, class: "col-md-3 required-a" %>
							<%= f.file_field :image, class: "mb-4 col-md-9", :placeholder => "アイコン画像をアップロード" %>
						</div>
					</div>
					<div class="update-content">
						<div class="row">
							<%= f.label :name, class: "col-md-3 required-a"%>
							<%= f.text_field :name, class: "form-control mb-4 col-md-9", :placeholder => "名前を入力" %>
						</div>
					</div>
					<div class="update-content">
						<div class="row">
							<%= f.label :introduction, class: "col-md-3 required-a" %>
							<%= f.text_area :introduction, rows: 5, class: "form-control mb-4 col-md-9", :placeholder => "自己紹介を入力" %>
						</div>
					</div>
					<div class="update-content">
						<div class="row">
							<%= f.submit "更新", class: "col-md-2 btn btn-primary mx-3" %>
						</div>
					</div>
				<% end %>
			</div>
		</div>
	</div>
</div>

app/views/users/show.html.erb
<div class="container-fiuld user">
	<div class="row">
		<div class="col-lg-2 user-nav user-nav-pc d-lg-block d-none">
			<ul>
				<li class="active"><%= link_to "アカウント", users_account_path %></li>
				<li class=""><%= link_to "プロフィール", users_profile_path %></li>
			</ul>
		</div>
		<div class="col-lg-2 user-nav user-nav-mobile d-lg-none">
			<ul>
				<li class="active"><%= link_to "アカウント", users_account_path %></li>
				<li class=""><%= link_to "プロフィール", users_profile_path %></li>
			</ul>
		</div>
		<div class="col-md-10 user-view">
			<div class="user-view-box">
				<div class="update-content">
					<div class="row">
						<h5>アカウント</h5>
					</div>
				</div>
				<div class="update-content">
					<div class="row">
						<label class="col-md-3" for="email">メールアドレス</label>
						<div class="col-md-9"><%= @user.email %></div>
					</div>
				</div>
				<div class="update-content">
					<div class="row">
						<label class="col-md-3" for="password">パスワード</label>
						<div class="col-md-9">*********</div>
					</div>
				</div>
				<div class="update-content">
					<div class="row">
						<%= link_to "編集", edit_user_registration_path, class: "col-md-2 btn btn-primary mx-3" %>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>